# import sys
# from .brd import IOS_learned_acl,IOS_learned_arp,IOS_learned_bgp,IOS_learned_dot1x,IOS_learned_interface,IOS_learned_lldp,IOS_learned_ntp,IOS_learned_ospf,IOS_learned_routing,IOS_learned_stp,IOS_learned_vlan,IOS_learned_vrf,IOS_show_access_lists,IOS_show_cdp_neighbors,IOS_show_cdp_neighbors_details,IOS_show_environment_all,IOS_show_etherchannel_summary,IOS_show_interfaces,IOS_show_interfaces_status,IOS_show_interfaces_trunk,IOS_show_inventory_9000,IOS_show_ip_arp,IOS_show_ip_interface_brief,IOS_show_ip_ospf,IOS_show_ip_ospf_database,IOS_show_ip_ospf_interface,IOS_show_ip_ospf_neighbor,IOS_show_ip_ospf_neighbor_detail,IOS_show_ip_route,IOS_show_license_summary,IOS_show_mac_address_table,IOS_show_ntp_associations,IOS_show_version,IOS_show_vlan,IOS_show_vrf,DNAC_Sites
# if __name__ == "__main__":
#     print(IOS_learned_acl(sys.argv[4]))
#     print(IOS_learned_arp(sys.argv[4]))
#     print(IOS_learned_bgp(sys.argv[4]))
#     print(IOS_learned_dot1x(sys.argv[4]))
#     print(IOS_learned_interface(sys.argv[4]))
#     print(IOS_learned_lldp(sys.argv[4]))
#     print(IOS_learned_ospf(sys.argv[4]))
#     print(IOS_learned_routing(sys.argv[4]))
#     print(IOS_learned_stp(sys.argv[4]))
#     print(IOS_learned_vlan(sys.argv[4]))
#     print(IOS_learned_vrf(sys.argv[4]))
#     print(IOS_show_access_lists_brief(sys.argv[4]))
#     print(IOS_show_cdp_neighbors_brief(sys.argv[4]))
#     print(IOS_show_cdp_neighbors_details_brief(sys.argv[4]))
#     print(IOS_show_environment_all(sys.argv[4]))
#     print(IOS_show_etherchannel_summary(sys.argv[4]))
#     print(IOS_show_interfaces(sys.argv[4]))
#     print(IOS_show_interfaces_status(sys.argv[4]))
#     print(IOS_show_interfaces_trunk(sys.argv[4]))
#     print(IOS_show_inventory_9000(sys.argv[4]))
#     print(IOS_show_ip_arp(sys.argv[4]))
#     print(IOS_show_ip_interface_brief(sys.argv[4]))
#     print(IOS_show_ip_ospf(sys.argv[4]))
#     print(IOS_show_ip_ospf_database(sys.argv[4]))
#     print(IOS_show_ip_ospf_interface(sys.argv[4]))
#     print(IOS_show_ip_ospf_neighbor(sys.argv[4]))
#     print(IOS_show_ip_ospf_neighbor_detail(sys.argv[4]))
#     print(IOS_show_ip_route(sys.argv[4]))
#     print(IOS_show_license_summary(sys.argv[4]))
#     print(IOS_show_mac_address_table(sys.argv[4]))
#     print(IOS_show_ntp_associations(sys.argv[4]))
#     print(IOS_show_version(sys.argv[4]))
#     print(IOS_show_vlan(sys.argv[4]))
#     print(IOS_show_vrf(sys.argv[4]))
#     print(DNAC_Sites(sys.argv[2]))